Data Generation

In [26]:
import pandas as pd
import numpy as np

# Define subjects
subjects = ['Math', 'Physics', 'English', 'History', 'Biology', 'Chemistry']

# Generate random data
num_students = 50
data = []
for i in range(num_students):
    student_data = {
        'Roll no.': i + 1,
        # 'Name': f'Student {i + 1}',
    }
    # Add random scores for each subject
    for subject in subjects:
        score = np.random.randint(50, 100)
        # Introduce 10% missing values randomly
        if np.random.rand() < 0.1:
            score = None
        # Introduce 5% outliers (very high or low scores)
        if np.random.rand() < 0.05:
            if np.random.rand() < 0.5:
                score = np.random.randint(-20, 0)
            else:
                score = np.random.randint(100, 120)
        student_data[subject] = score
    data.append(student_data)

# Create DataFrame
df = pd.DataFrame(data)

# Print the dataset
print(df)

    Roll no.   Math  Physics  English  History  Biology  Chemistry
0          1   60.0     64.0     95.0     87.0     78.0       88.0
1          2   99.0     -1.0      NaN     86.0    102.0       50.0
2          3   53.0     94.0     56.0     64.0     51.0       92.0
3          4   72.0     94.0      NaN     73.0     84.0        NaN
4          5   97.0     92.0     73.0     61.0     99.0       74.0
5          6   83.0     91.0     87.0    -17.0     71.0       98.0
6          7    NaN     83.0     96.0     65.0     56.0       84.0
7          8   54.0     70.0     56.0     92.0     94.0       80.0
8          9   64.0     88.0     51.0      NaN     97.0       95.0
9         10   61.0     57.0     59.0     92.0     67.0       75.0
10        11   85.0     78.0      NaN     82.0     82.0       53.0
11        12   64.0     87.0    -13.0     94.0     89.0       68.0
12        13   60.0     50.0     78.0     83.0     88.0       98.0
13        14   98.0     71.0     60.0     74.0     80.0       70.0
14        15   97.0     61.0      NaN     98.0     73.0       85.0
15        16   73.0     77.0     55.0     86.0    101.0       50.0
16        17   -8.0     86.0     74.0     80.0     86.0      115.0
17        18    NaN     99.0     67.0     50.0     79.0        NaN
18        19   72.0     69.0     58.0     80.0     70.0       91.0
19        20   96.0     89.0     79.0     73.0     69.0       89.0
20        21   76.0     82.0     58.0     78.0     56.0       83.0
21        22   69.0     65.0     86.0     79.0     90.0       98.0
22        23   67.0     98.0     95.0     88.0     68.0       81.0
23        24   96.0     53.0     59.0     92.0     56.0        NaN
24        25   63.0      NaN     63.0     81.0      NaN       85.0
25        26   91.0     98.0     58.0     58.0     61.0       53.0
26        27   53.0      NaN     59.0     67.0     55.0       93.0
27        28   70.0     99.0    -19.0     93.0      NaN       70.0
28        29   79.0     61.0      NaN     79.0     99.0       87.0
29        30  -16.0     95.0     81.0     76.0     65.0       53.0
30        31   68.0     67.0     83.0     51.0      NaN       51.0
31        32  110.0     95.0     82.0     90.0     52.0       80.0
32        33  107.0     62.0     96.0     99.0     95.0        NaN
33        34   68.0     90.0     91.0     59.0     76.0       98.0
34        35  107.0     88.0     59.0     68.0     75.0       63.0
35        36   54.0     82.0     72.0     68.0     93.0       79.0
36        37   96.0     65.0     53.0     65.0     83.0       61.0
37        38   60.0     72.0     94.0     60.0     -5.0      114.0
38        39   58.0     56.0     50.0     92.0      NaN       62.0
39        40   83.0      NaN     75.0     81.0     80.0       72.0
40        41   57.0     67.0     87.0     50.0     61.0       74.0
41        42   71.0     60.0     72.0     55.0     53.0       67.0
42        43   89.0     65.0      NaN     61.0      NaN      104.0
43        44   52.0     93.0     51.0     67.0     81.0       82.0
44        45   59.0     86.0     64.0     76.0     52.0       50.0
45        46   51.0     73.0     73.0     89.0     72.0       91.0
46        47   59.0     85.0     61.0     54.0     51.0       91.0
47        48   80.0     72.0     58.0     64.0     93.0       76.0
48        49   75.0     84.0     98.0     94.0    110.0       75.0
49        50   58.0     73.0     90.0     72.0     74.0        NaN

Objective 1: Dealing with missing values and inconsistencies

In [27]:
# Handling missing values for numeric columns only
df_numeric = df.select_dtypes(include=[np.number])
df_numeric.fillna(0, inplace=True)

# Checking for missing values again
print("Missing Values After Handling:")
print(df_numeric.isnull().sum())

print(df_numeric)

Missing Values After Handling:
Roll no.     0
Math         0
Physics      0
English      0
History      0
Biology      0
Chemistry    0
dtype: int64
    Roll no.   Math  Physics  English  History  Biology  Chemistry
0          1   60.0     64.0     95.0     87.0     78.0       88.0
1          2   99.0     -1.0      0.0     86.0    102.0       50.0
2          3   53.0     94.0     56.0     64.0     51.0       92.0
3          4   72.0     94.0      0.0     73.0     84.0        0.0
4          5   97.0     92.0     73.0     61.0     99.0       74.0
5          6   83.0     91.0     87.0    -17.0     71.0       98.0
6          7    0.0     83.0     96.0     65.0     56.0       84.0
7          8   54.0     70.0     56.0     92.0     94.0       80.0
8          9   64.0     88.0     51.0      0.0     97.0       95.0
9         10   61.0     57.0     59.0     92.0     67.0       75.0
10        11   85.0     78.0      0.0     82.0     82.0       53.0
11        12   64.0     87.0    -13.0     94.0     89.0       68.0
12        13   60.0     50.0     78.0     83.0     88.0       98.0
13        14   98.0     71.0     60.0     74.0     80.0       70.0
14        15   97.0     61.0      0.0     98.0     73.0       85.0
15        16   73.0     77.0     55.0     86.0    101.0       50.0
16        17   -8.0     86.0     74.0     80.0     86.0      115.0
17        18    0.0     99.0     67.0     50.0     79.0        0.0
18        19   72.0     69.0     58.0     80.0     70.0       91.0
19        20   96.0     89.0     79.0     73.0     69.0       89.0
20        21   76.0     82.0     58.0     78.0     56.0       83.0
21        22   69.0     65.0     86.0     79.0     90.0       98.0
22        23   67.0     98.0     95.0     88.0     68.0       81.0
23        24   96.0     53.0     59.0     92.0     56.0        0.0
24        25   63.0      0.0     63.0     81.0      0.0       85.0
25        26   91.0     98.0     58.0     58.0     61.0       53.0
26        27   53.0      0.0     59.0     67.0     55.0       93.0
27        28   70.0     99.0    -19.0     93.0      0.0       70.0
28        29   79.0     61.0      0.0     79.0     99.0       87.0
29        30  -16.0     95.0     81.0     76.0     65.0       53.0
30        31   68.0     67.0     83.0     51.0      0.0       51.0
31        32  110.0     95.0     82.0     90.0     52.0       80.0
32        33  107.0     62.0     96.0     99.0     95.0        0.0
33        34   68.0     90.0     91.0     59.0     76.0       98.0
34        35  107.0     88.0     59.0     68.0     75.0       63.0
35        36   54.0     82.0     72.0     68.0     93.0       79.0
36        37   96.0     65.0     53.0     65.0     83.0       61.0
37        38   60.0     72.0     94.0     60.0     -5.0      114.0
38        39   58.0     56.0     50.0     92.0      0.0       62.0
39        40   83.0      0.0     75.0     81.0     80.0       72.0
40        41   57.0     67.0     87.0     50.0     61.0       74.0
41        42   71.0     60.0     72.0     55.0     53.0       67.0
42        43   89.0     65.0      0.0     61.0      0.0      104.0
43        44   52.0     93.0     51.0     67.0     81.0       82.0
44        45   59.0     86.0     64.0     76.0     52.0       50.0
45        46   51.0     73.0     73.0     89.0     72.0       91.0
46        47   59.0     85.0     61.0     54.0     51.0       91.0
47        48   80.0     72.0     58.0     64.0     93.0       76.0
48        49   75.0     84.0     98.0     94.0    110.0       75.0
49        50   58.0     73.0     90.0     72.0     74.0        0.0

Objective 2: Detecting and handling outliers

In [28]:
# Handling outliers for numeric columns only
df_numeric = df_numeric.select_dtypes(include=[np.number])


# Define upper and lower bounds for outliers
lower_bound = 0
upper_bound = 100

# Handling outliers by replacing them with the closest non-outlier value
for col in df_numeric.columns:
    df_numeric[col] = np.where(df_numeric[col] < lower_bound, lower_bound, df_numeric[col ])
    df_numeric[col] = np.where(df_numeric[col] > upper_bound, lower_bound, df_numeric[col])

# Checking for outliers again
print("Outliers After Handling:")
print(df_numeric)

Outliers After Handling:
    Roll no.  Math  Physics  English  History  Biology  Chemistry
0          1  60.0     64.0     95.0     87.0     78.0       88.0
1          2  99.0      0.0      0.0     86.0      0.0       50.0
2          3  53.0     94.0     56.0     64.0     51.0       92.0
3          4  72.0     94.0      0.0     73.0     84.0        0.0
4          5  97.0     92.0     73.0     61.0     99.0       74.0
5          6  83.0     91.0     87.0      0.0     71.0       98.0
6          7   0.0     83.0     96.0     65.0     56.0       84.0
7          8  54.0     70.0     56.0     92.0     94.0       80.0
8          9  64.0     88.0     51.0      0.0     97.0       95.0
9         10  61.0     57.0     59.0     92.0     67.0       75.0
10        11  85.0     78.0      0.0     82.0     82.0       53.0
11        12  64.0     87.0      0.0     94.0     89.0       68.0
12        13  60.0     50.0     78.0     83.0     88.0       98.0
13        14  98.0     71.0     60.0     74.0     80.0       70.0
14        15  97.0     61.0      0.0     98.0     73.0       85.0
15        16  73.0     77.0     55.0     86.0      0.0       50.0
16        17   0.0     86.0     74.0     80.0     86.0        0.0
17        18   0.0     99.0     67.0     50.0     79.0        0.0
18        19  72.0     69.0     58.0     80.0     70.0       91.0
19        20  96.0     89.0     79.0     73.0     69.0       89.0
20        21  76.0     82.0     58.0     78.0     56.0       83.0
21        22  69.0     65.0     86.0     79.0     90.0       98.0
22        23  67.0     98.0     95.0     88.0     68.0       81.0
23        24  96.0     53.0     59.0     92.0     56.0        0.0
24        25  63.0      0.0     63.0     81.0      0.0       85.0
25        26  91.0     98.0     58.0     58.0     61.0       53.0
26        27  53.0      0.0     59.0     67.0     55.0       93.0
27        28  70.0     99.0      0.0     93.0      0.0       70.0
28        29  79.0     61.0      0.0     79.0     99.0       87.0
29        30   0.0     95.0     81.0     76.0     65.0       53.0
30        31  68.0     67.0     83.0     51.0      0.0       51.0
31        32   0.0     95.0     82.0     90.0     52.0       80.0
32        33   0.0     62.0     96.0     99.0     95.0        0.0
33        34  68.0     90.0     91.0     59.0     76.0       98.0
34        35   0.0     88.0     59.0     68.0     75.0       63.0
35        36  54.0     82.0     72.0     68.0     93.0       79.0
36        37  96.0     65.0     53.0     65.0     83.0       61.0
37        38  60.0     72.0     94.0     60.0      0.0        0.0
38        39  58.0     56.0     50.0     92.0      0.0       62.0
39        40  83.0      0.0     75.0     81.0     80.0       72.0
40        41  57.0     67.0     87.0     50.0     61.0       74.0
41        42  71.0     60.0     72.0     55.0     53.0       67.0
42        43  89.0     65.0      0.0     61.0      0.0        0.0
43        44  52.0     93.0     51.0     67.0     81.0       82.0
44        45  59.0     86.0     64.0     76.0     52.0       50.0
45        46  51.0     73.0     73.0     89.0     72.0       91.0
46        47  59.0     85.0     61.0     54.0     51.0       91.0
47        48  80.0     72.0     58.0     64.0     93.0       76.0
48        49  75.0     84.0     98.0     94.0      0.0       75.0
49        50  58.0     73.0     90.0     72.0     74.0        0.0

Objective 3: Applying data transformations

In [29]:
# Applying data transformations
# For example, we can apply min-max scaling to the scores to change their scale to a common range (0 to 1)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
# Filling missing values again before transformation
df_numeric.fillna(df_numeric.mean(), inplace=True)

# Applying data transformations
scaler = MinMaxScaler()
df_numeric[subjects] = scaler.fit_transform(df_numeric[subjects])

# Checking the transformed data
print("Transformed Data:")
print(df_numeric)

Transformed Data:
    Roll no.      Math   Physics   English   History   Biology  Chemistry
0          1  0.606061  0.646465  0.969388  0.878788  0.787879   0.897959
1          2  1.000000  0.000000  0.000000  0.868687  0.000000   0.510204
2          3  0.535354  0.949495  0.571429  0.646465  0.515152   0.938776
3          4  0.727273  0.949495  0.000000  0.737374  0.848485   0.000000
4          5  0.979798  0.929293  0.744898  0.616162  1.000000   0.755102
5          6  0.838384  0.919192  0.887755  0.000000  0.717172   1.000000
6          7  0.000000  0.838384  0.979592  0.656566  0.565657   0.857143
7          8  0.545455  0.707071  0.571429  0.929293  0.949495   0.816327
8          9  0.646465  0.888889  0.520408  0.000000  0.979798   0.969388
9         10  0.616162  0.575758  0.602041  0.929293  0.676768   0.765306
10        11  0.858586  0.787879  0.000000  0.828283  0.828283   0.540816
11        12  0.646465  0.878788  0.000000  0.949495  0.898990   0.693878
12        13  0.606061  0.505051  0.795918  0.838384  0.888889   1.000000
13        14  0.989899  0.717172  0.612245  0.747475  0.808081   0.714286
14        15  0.979798  0.616162  0.000000  0.989899  0.737374   0.867347
15        16  0.737374  0.777778  0.561224  0.868687  0.000000   0.510204
16        17  0.000000  0.868687  0.755102  0.808081  0.868687   0.000000
17        18  0.000000  1.000000  0.683673  0.505051  0.797980   0.000000
18        19  0.727273  0.696970  0.591837  0.808081  0.707071   0.928571
19        20  0.969697  0.898990  0.806122  0.737374  0.696970   0.908163
20        21  0.767677  0.828283  0.591837  0.787879  0.565657   0.846939
21        22  0.696970  0.656566  0.877551  0.797980  0.909091   1.000000
22        23  0.676768  0.989899  0.969388  0.888889  0.686869   0.826531
23        24  0.969697  0.535354  0.602041  0.929293  0.565657   0.000000
24        25  0.636364  0.000000  0.642857  0.818182  0.000000   0.867347
25        26  0.919192  0.989899  0.591837  0.585859  0.616162   0.540816
26        27  0.535354  0.000000  0.602041  0.676768  0.555556   0.948980
27        28  0.707071  1.000000  0.000000  0.939394  0.000000   0.714286
28        29  0.797980  0.616162  0.000000  0.797980  1.000000   0.887755
29        30  0.000000  0.959596  0.826531  0.767677  0.656566   0.540816
30        31  0.686869  0.676768  0.846939  0.515152  0.000000   0.520408
31        32  0.000000  0.959596  0.836735  0.909091  0.525253   0.816327
32        33  0.000000  0.626263  0.979592  1.000000  0.959596   0.000000
33        34  0.686869  0.909091  0.928571  0.595960  0.767677   1.000000
34        35  0.000000  0.888889  0.602041  0.686869  0.757576   0.642857
35        36  0.545455  0.828283  0.734694  0.686869  0.939394   0.806122
36        37  0.969697  0.656566  0.540816  0.656566  0.838384   0.622449
37        38  0.606061  0.727273  0.959184  0.606061  0.000000   0.000000
38        39  0.585859  0.565657  0.510204  0.929293  0.000000   0.632653
39        40  0.838384  0.000000  0.765306  0.818182  0.808081   0.734694
40        41  0.575758  0.676768  0.887755  0.505051  0.616162   0.755102
41        42  0.717172  0.606061  0.734694  0.555556  0.535354   0.683673
42        43  0.898990  0.656566  0.000000  0.616162  0.000000   0.000000
43        44  0.525253  0.939394  0.520408  0.676768  0.818182   0.836735
44        45  0.595960  0.868687  0.653061  0.767677  0.525253   0.510204
45        46  0.515152  0.737374  0.744898  0.898990  0.727273   0.928571
46        47  0.595960  0.858586  0.622449  0.545455  0.515152   0.928571
47        48  0.808081  0.727273  0.591837  0.646465  0.939394   0.775510
48        49  0.757576  0.848485  1.000000  0.949495  0.000000   0.765306
49        50  0.585859  0.737374  0.918367  0.727273  0.747475   0.000000